library('wordcloud')
library('RColorBrewer')
conventions <- read.csv('[filename]', header = TRUE,sep = ',')
png('[img]', width=500,height=500)
wordcloud(conventions[,1], conventions[,2],scale = c(10,1), colors = brewer.pal(8,'Dark2'), rot.per = 0.25)
dev.off()